version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shepscan_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: shep
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shepscan
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shepscan_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
